"use strict";
let car = "Revo";
console.log("is car=='Revo'?I predict true");
console.log(car == 'Revo');
console.log("is car!='Revo'?I predict false");
console.log(car != 'Revo');
let education = "Bcs";
console.log("is education=='Bcs'?I predict true");
console.log(education == "Bcs");
console.log("is education!='Bcs'?I predict false");
console.log(education != 'Bcs');
let country = "pakistan";
console.log("is country=='pakistan'?I predict true");
console.log(country == "pakistan");
console.log("is country!='pakistan'?I predict false");
console.log(country != 'pakistan');
let y = 30;
console.log("is y=='30'?I predict true");
console.log(y == 30);
console.log("is y!='30'?I predict false");
console.log(y != 30);
let isbusinessman = true;
console.log("is businessman ==true?I predict true");
console.log(isbusinessman == true);
console.log("is businessman !=true?I predict false");
console.log(isbusinessman != true);
